### ISSUE TITLE
std::error::Error is not implemented for decode::Error

### ISSUE THREAD

**Issue by tmladek** [paritytech/unsigned-varint#35]
This makes it inconvenient to convert from, as is the case when using `anyhow`, for instance:

```rust
pub fn decode(buffer: &Vec<u8>) -> anyhow::Result<Self> {
        let (obj_type, rest) = unsigned_varint::decode::u128(buffer)?;
        // ...snip
}
```

```
^ the trait `std::error::Error` is not implemented for `unsigned_varint::decode::Error`
```

**Comment by twittner** [comment]
The `std::error::Error` impl requires the `std` feature: https://github.com/paritytech/unsigned-varint/blob/master/src/decode.rs#L43-L44

**Comment by tmladek** [comment]
Oh! Didn't see that anywhere in the docs (and must have missed it looking through the source). Thank you!

Well, my issue is solved then, but I wonder whether this should be mentioned somewhere?

**Comment by twittner** [comment]
I agree. PR https://github.com/paritytech/unsigned-varint/pull/36 should fix that.

**Comment by tmladek** [comment]
Thank you kindly.
